apiVersion: v1
kind: Service
metadata:
  name: {{ include "wovyr.fullname" . }}
  labels:
    {{- include "wovyr.labels" . | nindent 4 }}
    {{- include "wovyr.server.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.wovyr.service.type }}
  ports:
    - name: http
      port: {{ .Values.wovyr.port }}
      targetPort: http
  selector:
    {{- include "wovyr.server.selectorLabels" . | nindent 4 }}
