#!/usr/bin/env python3
"""Regenerate `docs/11-cli/commands.md` from the real clap command tree (DX-304).

Walks `wovyr --help` recursively (every `Commands:` entry, `help` excluded) and
emits one section per command path with its verbatim `--help` output — so the
reference can never describe a command that doesn't exist, nor omit one that
does. CI regenerates the doc and fails on a diff against the committed copy.

Usage:
    cargo build -p wovyr-cli
    python3 scripts/gen-cli-docs.py [--check]

`--check` regenerates to a temp buffer and exits non-zero if the committed
doc differs (the CI mode); without it, the doc is rewritten in place.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BINARY = REPO / "target" / "debug" / "wovyr"
DOC = REPO / "docs" / "11-cli" / "commands.md"


def help_text(path: list[str]) -> str:
    out = subprocess.run(
        [str(BINARY), *path, "--help"], capture_output=True, text=True, check=True
    )
    return out.stdout.rstrip("\n")


def subcommands(help_output: str) -> list[str]:
    """Command names listed under `Commands:` (clap's fixed layout), minus the
    auto-generated `help`."""
    names: list[str] = []
    in_commands = False
    for line in help_output.splitlines():
        if line.strip() == "Commands:":
            in_commands = True
            continue
        if in_commands:
            if not line.startswith("  ") or not line.strip():
                break
            m = re.match(r"^  (\S+)", line)
            if m and m.group(1) != "help":
                names.append(m.group(1))
    return names


def walk(path: list[str], sections: list[tuple[list[str], str]]) -> None:
    text = help_text(path)
    sections.append((path, text))
    for name in subcommands(text):
        walk([*path, name], sections)


def render(sections: list[tuple[list[str], str]], version: str) -> str:
    lines = [
        "<!--",
        "File: docs/11-cli/commands.md",
        "Document ID: CLI-003",
        "GENERATED by scripts/gen-cli-docs.py — do not edit by hand.",
        "Regenerate: cargo build -p wovyr-cli && python3 scripts/gen-cli-docs.py",
        "CI regenerates and diffs this file, so drift fails the build (DX-304).",
        "-->",
        "",
        "# CLI Command Reference",
        "",
        "**Document ID:** CLI-003  ",
        "**File Path:** `docs/11-cli/commands.md`  ",
        f"**Version:** generated from `wovyr {version}`  ",
        "**Status:** Generated (from the clap command tree)  ",
        "**Owner:** AI Platform Team",
        "",
        "---",
        "",
        "Every section below is the verbatim `--help` output of a real command —",
        "generated, so the reference can never describe a command that doesn't",
        "exist, nor omit one that does. Conceptual docs live in",
        "[overview.md](overview.md) and [configuration.md](configuration.md).",
        "",
    ]
    for path, text in sections:
        title = " ".join(["wovyr", *path[: len(path)]]) if path else "wovyr"
        lines.append(f"## `{title}`")
        lines.append("")
        lines.append("```text")
        lines.append(text)
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not BINARY.exists():
        print(f"error: {BINARY} not built — run `cargo build -p wovyr-cli` first", file=sys.stderr)
        return 2
    version_out = subprocess.run(
        [str(BINARY), "--version"], capture_output=True, text=True, check=True
    ).stdout.strip()
    version = version_out.split()[-1]

    sections: list[tuple[list[str], str]] = []
    walk([], sections)
    doc = render(sections, version)

    if "--check" in sys.argv:
        current = DOC.read_text() if DOC.exists() else ""
        if current != doc:
            print(
                f"error: {DOC.relative_to(REPO)} is stale — regenerate with "
                "`python3 scripts/gen-cli-docs.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{DOC.relative_to(REPO)} is up to date ({len(sections)} commands)")
        return 0

    DOC.write_text(doc)
    print(f"wrote {DOC.relative_to(REPO)} ({len(sections)} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
