apiVersion: v1
kind: Service
metadata:
  name: {{ include "apex.fullname" . }}
  labels:
    {{- include "apex.labels" . | nindent 4 }}
    {{- include "apex.server.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apex.service.type }}
  ports:
    - name: http
      port: {{ .Values.apex.port }}
      targetPort: http
  selector:
    {{- include "apex.server.selectorLabels" . | nindent 4 }}
